/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.sridharan.sample;

import org.jspecify.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class Library {
    @Nullable String nullableMemberField;

    public int someLibraryMethod(@Nullable String nullableFunctionArgument) {
        if (nullableFunctionArgument != null) {
            var future = CompletableFuture.completedFuture("foo").thenApply(foo -> {
                return nullableFunctionArgument.length();
            });
            return future.join();
        }
        if (nullableMemberField != null) {
            var future = CompletableFuture.completedFuture("foo").thenApply(foo -> {
                return nullableMemberField.length();
            });
            return future.join();
        }
        return 0;
    }
}
