/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.sridharan.sample;

public class Library {
    public boolean someLibraryMethod() {

        Object x = null;
        return x.hashCode() == 0;
    }

    public enum SomeEnum {
        A,
        B,
    }

    public int exhaustiveSwitch(SomeEnum e) {
        String s = null;
        switch (e) {
            case A -> {
                s = "A";
            }
            case B -> throw new RuntimeException();
        }
        return s.length();
    }
}
